---
driver:
  name: vagrant
  customize:
    memory: 2048
    cpus: 4
  synced_folders:
  - ['.', '/tmp/vagrant']
  network:
  - ["forwarded_port", {guest: 80,  host: 8080, auto_correct: true}]
  - ["forwarded_port", {guest: 443, host: 8443, auto_correct: true}]
  attributes:
    gerrit:
      config:
        auth:
          registerEmailPrivateKey: 123123123
          restTokenPrivateKey: 123123123

provisioner:
  name: chef_zero
#  config:
#    log_level: debug

verifier:
  name: inspec

platforms:
  - name: debian-8.9
    attributes:
      apt:
        compile_time_update: true
    run_list:
      - recipe[apt::default]

suites:
  - name: default
    run_list:
      - recipe[site-reviewtypo3org::default]
      - recipe[site-reviewtypo3org_test::default]
    attributes:
      gerrit:
        config:
          auth:
            registerEmailPrivateKey: 123123123
            restTokenPrivateKey: 123123123
            cookieSecure: false
          ldap:
            username: <%= ENV['GERRIT_LDAP_USER'] || 'cn=review-dev.typo3.org,ou=services,dc=typo3,dc=org' %>
            password: <%= ENV['GERRIT_LDAP_PASSWORD'] %>
          gerrit:
            canonicalWebUrl: http://192.168.88.11:8080/
            canonicalGitUrl: git://git.vagrant
          httpd:
            listenUrl: http://*:8080/
        hostname: review.vagrant
      gitweb:
        hostname: git.vagrant
        ssl_certificate: wildcard.vagrant
      mysql:
        server_root_password: root
    driver_config:
       network:
         - ["private_network", {ip: "192.168.88.11"}]

  - name: proxy
    run_list:
      - recipe[site-reviewtypo3org::default]
      - recipe[site-reviewtypo3org_test::default]
      - recipe[site-reviewtypo3org_test::proxy]
    attributes:
      dev_mode: true
      gerrit:
        config:
          auth:
            registerEmailPrivateKey: 123123123
            restTokenPrivateKey: 123123123
            cookieSecure: false
          gerrit:
            canonicalWebUrl: https://review.vagrant
            canonicalGitUrl: git://git.vagrant
        hostname: review.vagrant
      gitweb:
        hostname: git.vagrant
        ssl_certificate: wildcard.vagrant
      mysql:
        server_root_password: root
    driver_config:
       network:
         - ["private_network", {ip: "192.168.88.12"}]

