---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian-7.4
    run_list:
    - recipe[apt::default]

suites:
  - name: default
    run_list:
      - recipe[site-reviewtypo3org::default]
    attributes:
      # this makes chef-vault use plaintext data bags
      dev_mode: true
      site-reviewtypo3org:
        amqp:
          server: mq.typo3.vagrant
          user: reviewtypo3org
