---
driver:
  name: vagrant
  customize:
    memory: 4096
    cpus: 4
  synced_folders:
  - ['.', '/tmp/vagrant']
  network:
  - ["forwarded_port", {guest: 80,  host: 8080, auto_correct: true}]
  - ["forwarded_port", {guest: 443, host: 8443, auto_correct: true}]
  - ["private_network", {ip: "192.168.88.11"}]
  attributes: 
    gerrit:
      config:
        auth:
          registerEmailPrivateKey: 123123123
          restTokenPrivateKey: 123123123


provisioner:
  name: chef_zero

platforms:
- name: debian-7.8
- name: debian-8.2

suites:
  - name: default
    run_list:
      - recipe[site-reviewtypo3org::default]
      - recipe[site-gittypo3org]
      - recipe[t3-gerrit::replication]
    attributes:
      # this makes chef-vault use plaintext data bags
      dev_mode: true
      gerrit:
        config:
          auth:
            registerEmailPrivateKey: 123123123
            restTokenPrivateKey: 123123123
        # version: 2.12
      site-gittypo3org:
        amqp:
          server: mq.typo3.vagrant
          user: reviewtypo3org
          vhost: test
      site-reviewtypo3org:
        amqp:
          server: mq.typo3.vagrant
          user: reviewtypo3org
          vhost: test
        hostname: review.vagrant
        canonicalWebUrl: https://review.vagrant
        canonicalGitUrl: git://git.vagrant
        proxy:
          ssl_cabundle: /etc/ssl_certs/wildcard.vagrant.ca-bundle
          ssl_certfile: /etc/ssl_certs/wildcard.vagrant.crt
          ssl_keyfile: /etc/ssl_certs/wildcard.vagrant.key
      gitweb:
        hostname: git.vagrant
        ssl_certificate: wildcard.vagrant
