name             "site-reviewtypo3org"
maintainer       "Steffen Gebert / TYPO3 Association"
maintainer_email "steffen.gebert@typo3.org"
license          "Apache 2.0"
description      "Installs/configures something"
version          "0.1.2"

depends "ssl_certificates"
depends "t3-gerrit"
depends "gerrit"
depends "t3-chef-vault"
