name             "site-reviewtypo3org"
maintainer       "Steffen Gebert / TYPO3 Association"
maintainer_email "steffen.gebert@typo3.org"
license          "Apache 2.0"
description      "Installs/configures something"
version          "0.1.30"

depends "ssh", "= 0.6.6"
depends "ssl_certificates", "= 1.1.3"
depends "t3-gerrit", "= 0.4.26"
depends "t3-chef-vault", "= 1.0.1"
depends "apt", "= 2.7.0"
depends "runit"
