name             "site-reviewtypo3org"
maintainer       "Steffen Gebert / TYPO3 Association"
maintainer_email "steffen.gebert@typo3.org"
license          "Apache 2.0"
description      "Installs/configures something"
version          "0.1.23"

depends "ssh", "= 0.6.6"
depends "ssl_certificates", "= 1.1.3"
depends "t3-gerrit", "= 0.4.20"
depends "gerrit", "= 0.4.5"
depends "t3-chef-vault", "= 1.0.1"
